### ISSUE TITLE
Enhancement: Convenient and opaque setup of nested `safely` blocks with retry tags

### ISSUE THREAD

**Issue by DarrenBishop** [BrunoBonacci/safely#6]
Clojure already appears to discourage custom exceptions with its offerings of `ex-info` and `ex-data`.

As an application's execution flows deeper into the call stack, it may encounter sections of code written at different times by different people, for each of which it may have been deemed prudent to wrap in a `safely` block.

To avoid one of a few custom exceptions, thrown from deep, from being retried at multiple levels as the call stack unwinds, a declarative signalling, where the overall application composition is opaque, could be useful.

The `:retryable? func` pair is a versatile option that will do the job.

However, there is a convenience in extending the API by way of a new `retryable? #{...}` tags option; the following entries could be supported in the `ex-info` `data`:
```
(ex-info "failed to ping external endpoint" {:tags #{:api :ping-endpoint} ...})
```

The corresponding `safely` options could correspondingly include:
```
(safely
  (ping external-endpoint ...)
  :on-error
  :max-retries 5
  :retryable? #{:ping-endpoint} ; Option 1: (if (and (set? retryable) (seq (intersection retryable (-> ex ex-data :tags)) ...)
  :retryable? :ping-endpoint ; or Option 2: (if (and (keyword? retryable) ((-> ex ex-data :tags) retryable)
  :retryable? (fn ...)) ; or Option 3, behave as before
```

Of course `:retryable?` does not need to be overloaded; `:retryable-tags` and `retryable-tag` can be supplied, or something else intuitive.

With these additional options, the API can offer similar versatility while remaining declarative (more so than declaring a func) and idiomatic (`ex-info`...)

In the abstract, it appears `compojure-api` implements a similar approach:
 * Here, the exception response logic is the same each time, retry (or not); there, exception response logic (the handler) is arbitrary, but typically constructs some non-`OK` HTTP response
* In this proposal, the discriminator to trigger the logic are`:tags` in the `ex-data`; there, it is a singular `:type` entry

There is the added end-user benefit that, with the logic of retrying tags pushed down and tested in the library, there is slightly less code and therefore less testing required in the application.

**Comment by BrunoBonacci** [comment]
Hi @DarrenBishop 
from what I understand what you really looking for is a way to write more expressive `:retryable?` predicates.

one solution could be to use [where](https://github.com/BrunoBonacci/where) library.

For example you can write things like:

``` clojure
(safely
  (ping external-endpoint ...)
  :on-error
  :max-retries 5
  :retryable?  (where type :in? [TimeoutException ConnectionException]))
```
or 

``` clojure
(where #(-> % ex-data :tags) :not-in? [:ping-endpoint :api :foo])
``` 
and even combine predicates with logical `AND` and `OR`.

**Comment by BrunoBonacci** [comment]
Hi @DarrenBishop,

my understanding from your comment on issue: #5 is that this is not
required any longer. Additionally, the `where` solution provides
a convenient alternative.

I will close this issue, if you feel strong about this feature
feel free to reopen and we will re-discuss.

Bruno
